server:
  port: 8080
  environment: dev

env-name: local
env-host: ${host}
donation-apply-notify: ${dingtalk-robot-address}


jwt:
  expiresIn: 18000
  secret: ${input-your-secret}

database:
  driver-name: mysql
  dsn: ${username}:${userpassword}@tcp(${db-host}:3306)/${dabase-name}?charset=utf8mb4&loc=Local
  max-lifetime: 6000
  max-open: 200
  max-idle-count: 100

redis:
  server: ${redis-host}:6379
  password:
  max-idle: 3
  max-active: 10

wechat:
  server: https://api.weixin.qq.com
  app-key: ${wechat-min-program-key}
  app-secret: ${wechat-min-program-secret}

log:
  level: debug
  output: stdout  # stdout,stderr, or file name
  report-caller: true

alioss:
  endpoint: ${oss-endpoint}
  accesskey-id: ${aliyun-acesskey-id}
  accesskey-secret: ${aliyun-accesskey-secret}
  bucket-name: ${bucket-name}
  domain: ${openview-oss.oss-cn-chengdu.aliyuncs.com}
  upload-dir: ${upload-dir}

kafka:
  boot-strap-servers: ${kafka-host}:9092
  topic: ${default-topic}

domain-event:
  server: ${kafka-host}:9092
  topic: ${domain-event-topic}
  group-id: ${domain-event-group-id}
  dead-letter-topic: ${dead-letter-topic}

tencent_map:
  apikey: ${tencent-map-apikey}
  apiksecret: ${tencent-map-apiksecret}
  tbl_device: ${tbl_device}

credential:
  url:
  appKey:
  appSecret:

evidence:
  url:
  appKey:
  appSecret:

aliyun-sms:
  access-key-id: ${aliyun-acesskey-id}
  access-key-secret: ${aliyun-accesskey-secret}
  enabled: false

mini-program-qrcode:
  content-root-path:

notifier:
  user-finder: tested



cpt-aed-cert:
cpt-medal:

backend:
  username:
  password:
  id:

//图片生成服务的地址
img-bot-service:

wechat-offiaccount-appid: ${wechat-offiaccount-appid}
wechat-offiaccount-secret: ${wechat-offiaccount-secret}